#!/bin/zsh 

# 		FIXME
for file in ~/.zsh/??_*; do
  source $file
done

source ~/src/z/z.sh

# vim: set ft=zsh

export PERL_LOCAL_LIB_ROOT="$PERL_LOCAL_LIB_ROOT:/home/noaht/perl5";
export PERL_MB_OPT="--install_base /home/noaht/perl5";
export PERL_MM_OPT="INSTALL_BASE=/home/noaht/perl5";
export PERL5LIB="/home/noaht/perl5/lib/perl5:$PERL5LIB";
export PATH="/home/noaht/perl5/bin:$PATH";

todo
