#!/bin/zsh 

# 		FIXME
for file in ~/.zsh/??_*; do
  source $file
done

source ~/src/z/z.sh

# vim: set ft=zsh

PATH="/home/noah/perl5/bin${PATH+:}${PATH}"; export PATH;
PERL5LIB="/home/noah/perl5/lib/perl5${PERL5LIB+:}${PERL5LIB}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/noah/perl5${PERL_LOCAL_LIB_ROOT+:}${PERL_LOCAL_LIB_ROOT}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/noah/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/noah/perl5"; export PERL_MM_OPT;

export MAIL=/home/noah/mail
